export const RESUME_TEXT = ` Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in suscipit metus. Sed mollis, tellus scelerisque mattis pharetra, augue elit hendrerit mi, ac consequat tellus mauris ut odio. Duis quis bibendum metus. Suspendisse gravida leo a lorem sollicitudin tempus. Phasellus ipsum diam, pretium vitae tortor sed, placerat feugiat odio. Nunc dui erat, fermentum aliquam sapien quis, interdum vulputate velit. Nunc fringilla volutpat tellus imperdiet egestas. Maecenas sed sem et massa euismod porta. Vivamus eget tincidunt magna. Etiam id placerat elit. Nulla consectetur porta felis non placerat. Vestibulum eget est venenatis est ornare molestie eget in nisl. Nam iaculis vulputate magna, nec euismod mauris lobortis sit amet.

Praesent maximus interdum purus id imperdiet. Donec quis bibendum magna. Donec auctor dolor mauris, pulvinar lobortis nunc dapibus in. Morbi eget ex hendrerit, pharetra turpis nec, hendrerit urna. Sed auctor sollicitudin justo. Curabitur tortor nunc, fermentum aliquam gravida nec, pellentesque a nulla. Nulla eget purus tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque non ante a purus condimentum aliquet vel aliquet augue. Morbi quam orci, efficitur eu erat ac, imperdiet consequat nunc. Pellentesque at tortor in ipsum commodo molestie at et erat. Sed sed elit vitae nulla tempor molestie. Cras justo massa, suscipit vitae fringilla sed, dignissim eget sapien. Duis sed dolor ut urna sagittis venenatis. Praesent quam metus, vehicula ac massa ac, hendrerit cursus felis.

Ut eget ligula venenatis, rutrum justo in, placerat tortor. Nam pretium feugiat orci, in laoreet metus porttitor in. Morbi quis massa et ligula rhoncus blandit sit amet sed felis. Sed tristique urna molestie ante imperdiet finibus. Praesent quis eros sagittis, efficitur nulla gravida, ultricies quam. Integer id malesuada ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras ut sollicitudin turpis. Aliquam non metus sit amet neque aliquam malesuada. Vivamus nec magna placerat, congue dolor vitae, sollicitudin nisl.

Morbi ac ante interdum, fringilla erat ac, pellentesque dolor. Nunc velit magna, gravida ac ante nec, malesuada blandit dolor. Nullam convallis eget nibh nec mollis. Donec vitae odio vestibulum, porta lectus in, bibendum nibh. Cras quis augue sed libero pellentesque elementum nec eget enim. Mauris vel blandit augue, in pretium lorem. Suspendisse convallis egestas justo et vulputate. Fusce consectetur convallis rhoncus. Ut nec lacus elementum, hendrerit sapien non, lacinia massa. Integer turpis urna, condimentum non purus a, luctus lobortis massa. Cras euismod orci tincidunt, tempor magna convallis, egestas ligula. Etiam vel volutpat felis, at ornare justo. Ut vitae diam quam.

Praesent molestie tellus et nunc dapibus, nec dapibus orci tempus. Pellentesque a accumsan neque. Pellentesque eget pretium dolor, vitae euismod sem. Quisque id turpis hendrerit est volutpat tincidunt. Cras sollicitudin sagittis odio eu rutrum. Cras fringilla efficitur elit, id luctus sapien auctor ut. Maecenas rhoncus massa leo, at pharetra urna feugiat at.`;

